version: '3'
services:
  app:
    container_name: azurecontainerinstances_demo
    restart: always
    image: mehul1887/azurecontainerinstances_demo
    ports:
      - 80:80
    networks:
      azurecontainerinstances:
        ipv4_address: 172.28.2.2

  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: -i 30 --cleanup 

networks:
  azurecontainerinstances:
    external: true
